<a href="https://colab.research.google.com/github/vakilarora/python/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

print('np version',np.__version__)

np version 1.25.2


In [ ]:
#Creating a 0-D numpy array
arr0 = np.array(100)

print('0-d np array',arr0)
print('type of 0-d np array',type(arr0))
print('dimentions of the 0-d np array',arr0.ndim)
print('the only element of 0-d np array',arr0)

0-d np array 100
type of 0-d np array <class 'numpy.ndarray'>
dimentions of the 0-d np array 0
the only element of 0-d np array 100


In [ ]:
#Creating a 1-D numpy array
arr1 = np.array([1,2,3,4,5])

print('1-d np array',arr1)
print('type of 1-d np array',type(arr1))
print('dimentions of the 1-d np array',arr1.ndim)
print('the first element of 1-d np array',arr1[0])

1-d np array [1 2 3 4 5]
type of 1-d np array <class 'numpy.ndarray'>
dimentions of the 1-d np array 1
the first element of 1-d np array 1


In [ ]:
#Creating a 2-D numpy array
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print('2-d np array',arr2)
print('type of 2-d np array',type(arr2))
print('dimentions of the 2-d np array',arr2.ndim)
print('the first element of 2-d np array',arr2[0,0])

2-d np array [[1 2 3]
 [4 5 6]
 [7 8 9]]
type of 2-d np array <class 'numpy.ndarray'>
dimentions of the 2-d np array 2
the first element of 2-d np array 1


In [ ]:
#Creating higher dimentional array
arr5 = np.array([[10, 20, 30, 40],[30,40,50,60]], ndmin=5)

print('5-d np array',arr5)
print('type of 5-d np array',type(arr5))
print('dimentions of the 5-d np array',arr5.ndim)
print('the first element of 5-d np array',arr5[0,0,0,0,0])

5-d np array [[[[[10 20 30 40]
    [30 40 50 60]]]]]
type of 5-d np array <class 'numpy.ndarray'>
dimentions of the 5-d np array 5
the first element of 5-d np array 10


In [ ]:
#Creating np array from tuples, sets, and the dictionaries
#Note: sets and dictionaries create 0-D array
arr11 = np.array((1,2,3))
arr12 = np.array({5,6,7,8})
arr13 = np.array({5:0,6:0,7:9,8:7})
print(arr11)
print(arr12)
print(arr13)

[1 2 3]
{8, 5, 6, 7}
{5: 0, 6: 0, 7: 9, 8: 7}


In [ ]:
#Slicing

arr21 = np.array([1, 2, 3, 4, 5, 6, 7])

arr22 = arr21[2:4]
arr23 = arr21[::2]
arr24 = arr21[-3,-1]
print('original array', arr21)
print('slice[2:4]',arr22)
print('slice[::2]',arr23)
print('slice[[-3,-1]]',arr24)

