<a href="https://colab.research.google.com/github/vakilarora/python/blob/main/Vector%20Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import math

In [4]:
v = np.array([1,2,3])
w = np.array([3,6,4])

In [5]:
vector_sum = v + w
print(vector_sum)

[4 8 7]


In [6]:
vector_diff = v - w
print(vector_diff)

[-2 -4 -1]


In [7]:
scalar = 5
scalar_mul = scalar * v
print(scalar_mul)

[ 5 10 15]


In [18]:
#Find length of a vector v
vector_length = np.linalg.norm(v)
print(vector_length)
print(math.sqrt(np.dot(v,v)))

3.7416573867739413
3.7416573867739413


In [17]:
#Dot product of two vectors
dot_product = np.dot(v,w)
print(dot_product)

27
